package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	_ "mongo-profiler/docs" // generated by swag init
	"mongo-profiler/src/config"
	"mongo-profiler/src/currentop"
	"mongo-profiler/src/indexstats"
	"mongo-profiler/src/replicaset"
	"mongo-profiler/src/snapshot"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

func NewMongodbConfig(config *config.Config) []string {
	host := config.Mongodb.Host
	username := config.Mongodb.Username
	password := config.Mongodb.Password

	if host == "" || username == "" || password == "" {
		log.Fatal("Missing required MongoDB environment variables")
	}

	var urls []string
	hosts := strings.Split(host, ",")
	for _, h := range hosts {
		trimmed := strings.TrimSpace(h)
		if trimmed == "" {
			continue
		}
		// encode username/password
		encodedUser := url.QueryEscape(username)
		encodedPass := url.QueryEscape(password)

		uri := fmt.Sprintf("mongodb://%s:%s@%s/?directConnection=true", encodedUser, encodedPass, trimmed)
		urls = append(urls, uri)
	}

	return urls
}

type handler struct {
	Config *config.Config

	MongoClients map[string]*mongo.Client
	Storage      *snapshot.Storage // dùng cho index correlation (Part 6)
}

func NewHandler(cfg *config.Config) *handler {
	mongoUrls := NewMongodbConfig(cfg)
	clients := make(map[string]*mongo.Client)

	// Tạo context dùng một lần để setup toàn bộ kết nối ban đầu
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	for _, u := range mongoUrls {
		fmt.Println("mongourl: ", u)
		parsed, err := url.Parse(u)
		if err != nil {
			log.Printf("Invalid MongoDB URL format: %v\n", err)
			continue
		}
		host := parsed.Hostname()

		clientOpts := options.Client().ApplyURI(u)
		client, err := mongo.Connect(clientOpts)
		if err != nil {
			log.Printf("Failed to create client for %s: %v\n", host, err)
			panic(err)
		}

		if err := client.Ping(ctx, nil); err != nil {
			log.Printf("Failed to ping %s: %v\n", host, err)
			panic(err)
		}

		log.Printf("Successfully connected to MongoDB: %s\n", host)
		clients[host] = client // Lưu vào map
	}

	return &handler{
		Config:       cfg,
		MongoClients: clients,
	}
}

type CountSystemProfileRequest struct {
	Databases string `form:"databases"`
}

type CountSystemProfileResult struct {
	URL      string  `json:"url"`
	Database string  `json:"database"`
	Count    int64   `json:"count"`
	Error    *string `json:"error,omitempty"`
}

type CountSystemProfileResponse struct {
	Results []CountSystemProfileResult `json:"results"`
}

// GetProfiles godoc
// @Summary     Đếm số slow query entries trong system.profile trên tất cả host
// @Description Trả về số lượng document trong system.profile của từng database trên mỗi MongoDB host đang giám sát.
// @Tags        profile
// @Produce     json
// @Param       databases  query  string  false  "Danh sách database cách nhau bằng dấu phẩy (bỏ trống = tất cả)"
// @Success     200  {object}  CountSystemProfileResponse
// @Failure     400  {object}  map[string]string
// @Router      /mongodb-cmd/profiles [get]
func (inst *handler) GetProfiles(c *gin.Context) {
	var query CountSystemProfileRequest
	if err := c.ShouldBindQuery(&query); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	var results []CountSystemProfileResult = make([]CountSystemProfileResult, 0)

	// 1. Phân tách danh sách databases từ user (nếu có)
	var userDBs []string
	if query.Databases != "" {
		for _, db := range strings.Split(query.Databases, ",") {
			trimmed := strings.TrimSpace(db)
			if trimmed != "" {
				userDBs = append(userDBs, trimmed)
			}
		}
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 30*time.Second)
	defer cancel()

	for host, client := range inst.MongoClients {
		targetDBs := userDBs

		if len(targetDBs) == 0 {
			dbNames, err := client.ListDatabaseNames(ctx, bson.M{})
			if err != nil {
				errMsg := err.Error()
				results = append(results, CountSystemProfileResult{
					URL:      host,
					Database: "",
					Count:    0,
					Error:    &errMsg,
				})
				continue // Chuyển sang server tiếp theo
			}
			targetDBs = dbNames
		}

		for _, dbName := range targetDBs {
			col := client.Database(dbName).Collection("system.profile")
			count, err := col.CountDocuments(ctx, bson.M{})

			if err != nil {
				errMsg := err.Error()
				results = append(results, CountSystemProfileResult{
					URL:      host,
					Database: dbName,
					Count:    0,
					Error:    &errMsg,
				})
			} else {
				results = append(results, CountSystemProfileResult{
					URL:      host,
					Database: dbName,
					Count:    count,
				})
			}
		}
	}

	c.JSON(http.StatusOK, CountSystemProfileResponse{Results: results})
}

type GetDatabaseProfileQuery struct {
	Endpoint     string `form:"endpoint" binding:"required"`
	Database     string `form:"database" binding:"required"`
	Limit        *int64 `form:"limit"`
	Offset       *int64 `form:"offset"`
	Collection   string `form:"collection"`
	Duration     *int64 `form:"duration"`
	OrderBy      string `form:"order_by"`
	OrderType    string `form:"order_type"` // "asc" hoặc "desc"
	Unique       *bool  `form:"unique"`
	From         string `form:"from"`
	To           string `form:"to"`
	IgnoreHashes string `form:"ignore_hashes"`
}

// GetProfile godoc
// @Summary     Lấy danh sách slow query từ system.profile
// @Description Truy vấn system.profile với nhiều tùy chọn lọc: collection, duration, thời gian, phân trang. Hỗ trợ chế độ unique để gom nhóm theo queryHash.
// @Tags        profile
// @Produce     json
// @Param       endpoint       query  string  true   "MongoDB host (ví dụ: 172.17.0.1:27017)"
// @Param       database       query  string  true   "Tên database"
// @Param       collection     query  string  false  "Lọc theo collection"
// @Param       duration       query  integer false  "Chỉ lấy query chậm hơn N ms"
// @Param       limit          query  integer false  "Số kết quả tối đa (mặc định 20)"
// @Param       offset         query  integer false  "Bỏ qua N kết quả đầu (phân trang)"
// @Param       order_by       query  string  false  "Field sắp xếp (mặc định: ts)"
// @Param       order_type     query  string  false  "asc hoặc desc (mặc định: desc)"
// @Param       unique         query  boolean false  "Gom nhóm theo queryHash, trả về thống kê"
// @Param       from           query  string  false  "RFC3339 — lấy từ thời điểm này (ví dụ: 2025-01-01T00:00:00Z)"
// @Param       to             query  string  false  "RFC3339 — lấy đến thời điểm này"
// @Param       ignore_hashes  query  string  false  "Bỏ qua những bản ghi có queryHash trong danh sách"
// @Success     200  {array}   map[string]interface{}
// @Failure     400  {object}  map[string]string
// @Failure     500  {object}  map[string]string
// @Router      /mongodb-cmd/profile [get]
func (inst *handler) GetProfile(c *gin.Context) {
	var query GetDatabaseProfileQuery

	if err := c.ShouldBindQuery(&query); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	client, exists := inst.MongoClients[query.Endpoint]
	if !exists {
		c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("Endpoint %s not found or disconnected", query.Endpoint)})
		return
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 10*time.Second)
	defer cancel()

	col := client.Database(query.Database).Collection("system.profile")

	filter := bson.M{} // Dùng bson.M cho Map không cần thứ tự
	if query.Collection != "" {
		filter["ns"] = fmt.Sprintf("%s.%s", query.Database, query.Collection)
	}
	if query.Duration != nil {
		filter["millis"] = bson.M{"$gt": *query.Duration}
	}

	if query.IgnoreHashes != "" {
		var ignoreHashes []string

		for _, hash := range strings.Split(query.IgnoreHashes, ",") {
			if trimmed := strings.TrimSpace(hash); trimmed != "" {
				ignoreHashes = append(ignoreHashes, trimmed)
			}
			if len(ignoreHashes) > 0 {
				filter["queryHash"] = bson.M{"$nin": ignoreHashes}
			}
		}
	}

	// Lọc theo thời gian trên field "ts" của system.profile
	if query.From != "" || query.To != "" {
		tsFilter := bson.M{}
		if query.From != "" {
			t, err := time.Parse(time.RFC3339, query.From)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid from (expect RFC3339): " + err.Error()})
				return
			}
			tsFilter["$gte"] = t
		}
		if query.To != "" {
			t, err := time.Parse(time.RFC3339, query.To)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid to (expect RFC3339): " + err.Error()})
				return
			}
			tsFilter["$lte"] = t
		}
		filter["ts"] = tsFilter
	}

	limit := int64(10000)
	if query.Limit != nil {
		limit = *query.Limit
	}
	offset := int64(0)
	if query.Offset != nil {
		offset = *query.Offset
	}

	sortField := "ts"
	if query.OrderBy != "" {
		sortField = query.OrderBy
	}

	sortDirection := -1
	if query.OrderType == "asc" {
		sortDirection = 1
	}

	isUnique := false
	if query.Unique != nil && *query.Unique {
		isUnique = true
	}

	if isUnique {
		// Dùng bson.D cho các operations yêu cầu tính thứ tự (như Pipeline)
		pipeline := mongo.Pipeline{
			{{Key: "$match", Value: filter}},
			// sort trước khi group
			{{Key: "$sort", Value: bson.D{{Key: sortField, Value: sortDirection}}}},
			// limit số lượng bản ghi trước khi group
			{{Key: "$limit", Value: limit}},
			{{Key: "$group", Value: bson.D{
				{Key: "_id", Value: "$queryHash"},
				{Key: "count", Value: bson.D{{Key: "$sum", Value: 1}}},
				{Key: "max_millis", Value: bson.D{{Key: "$max", Value: "$millis"}}},
				{Key: "avg_millis", Value: bson.D{{Key: "$avg", Value: "$millis"}}},
				{Key: "latest_ts", Value: bson.D{{Key: "$max", Value: "$ts"}}},
				{Key: "sample_ns", Value: bson.D{{Key: "$first", Value: "$ns"}}},
			}}},
			{{Key: "$sort", Value: bson.D{{Key: "count", Value: -1}}}}, // Xếp theo query xuất hiện nhiều nhất
			{{Key: "$skip", Value: offset}},
			{{Key: "$limit", Value: 5}}, // mặc định limit là 5
		}

		cursor, err := col.Aggregate(ctx, pipeline)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		var results []bson.M
		if err = cursor.All(ctx, &results); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		if results == nil {
			results = []bson.M{}
		}
		c.JSON(http.StatusOK, results)

	} else {
		findOptions := options.Find().
			SetSort(bson.D{{Key: sortField, Value: sortDirection}}).
			SetLimit(limit).
			SetSkip(offset)

		cursor, err := col.Find(ctx, filter, findOptions)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		var results []bson.M
		if err = cursor.All(ctx, &results); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		if results == nil {
			results = []bson.M{}
		}
		c.JSON(http.StatusOK, results)
	}
}

// newStorageClient tạo MongoDB client để lưu snapshot.
// Nếu storage.uri được cấu hình thì dùng trực tiếp URI đó.
// Ngược lại, build multi-host URI từ mongodb config (RS-aware, không directConnection).
func newStorageClient(cfg *config.Config) (*mongo.Client, error) {
	var uri string
	if cfg.Storage.URI != "" {
		uri = cfg.Storage.URI
		log.Printf("Storage: using configured storage.uri")
	} else {
		hosts := strings.Split(cfg.Mongodb.Host, ",")
		var trimmedHosts []string
		for _, h := range hosts {
			h = strings.TrimSpace(h)
			if h != "" {
				trimmedHosts = append(trimmedHosts, h)
			}
		}
		if len(trimmedHosts) == 0 {
			return nil, fmt.Errorf("no valid mongodb hosts in config")
		}
		encodedUser := url.QueryEscape(cfg.Mongodb.Username)
		encodedPass := url.QueryEscape(cfg.Mongodb.Password)
		// Nối tất cả host → driver tự discover replica set, không dùng directConnection
		uri = fmt.Sprintf("mongodb://%s:%s@%s/", encodedUser, encodedPass, strings.Join(trimmedHosts, ","))
		log.Printf("Storage: using mongodb config hosts (%s)", strings.Join(trimmedHosts, ","))
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	clientOpts := options.Client().ApplyURI(uri)
	client, err := mongo.Connect(clientOpts)
	if err != nil {
		return nil, fmt.Errorf("storage connect error: %w", err)
	}
	if err := client.Ping(ctx, nil); err != nil {
		return nil, fmt.Errorf("storage ping error: %w", err)
	}
	log.Println("Successfully connected to storage MongoDB")
	return client, nil
}

type DeleteProfileByQueryHashRequest struct {
	Endpoint  string `json:"endpoint"   binding:"required"`
	Database  string `json:"database"   binding:"required"`
	QueryHash string `json:"query_hash" binding:"required"`
}

type DeleteProfileByQueryHashResponse struct {
	Endpoint     string `json:"endpoint"`
	Database     string `json:"database"`
	QueryHash    string `json:"query_hash"`
	DeletedCount int64  `json:"deleted_count"`
}

// DeleteProfileByQueryHash godoc
// @Summary     Xóa slow query entries theo queryHash
// @Description Xóa tất cả document trong system.profile có queryHash khớp với giá trị yêu cầu.
// @Tags        profile
// @Accept      json
// @Produce     json
// @Param       body  body      DeleteProfileByQueryHashRequest  true  "Thông tin xóa"
// @Success     200   {object}  DeleteProfileByQueryHashResponse
// @Failure     400   {object}  map[string]string
// @Failure     500   {object}  map[string]string
// @Router      /mongodb-cmd/profile/query-hash [delete]
func (inst *handler) DeleteProfileByQueryHash(c *gin.Context) {
	var req DeleteProfileByQueryHashRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	client, exists := inst.MongoClients[req.Endpoint]
	if !exists {
		c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("endpoint %s not found or disconnected", req.Endpoint)})
		return
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 30*time.Second)
	defer cancel()

	col := client.Database(req.Database).Collection("system.profile")
	result, err := col.DeleteMany(ctx, bson.M{"queryHash": req.QueryHash})
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, DeleteProfileByQueryHashResponse{
		Endpoint:     req.Endpoint,
		Database:     req.Database,
		QueryHash:    req.QueryHash,
		DeletedCount: result.DeletedCount,
	})
}

// ─── Snapshot Retention ───────────────────────────────────────────────────────

type DeleteSnapshotsQuery struct {
	// before là RFC3339 — xóa tất cả snapshot có captured_at trước thời điểm này
	Before   string `form:"before" binding:"required"`
	Endpoint string `form:"endpoint"` // tuỳ chọn, bỏ trống = tất cả endpoint
}

type DeleteSnapshotsResponse struct {
	Before       string `json:"before"`
	Endpoint     string `json:"endpoint,omitempty"`
	DeletedCount int64  `json:"deleted_count"`
}

// DeleteSnapshots godoc
// @Summary     Xóa snapshot cũ để giải phóng storage
// @Description Xóa tất cả index snapshot có captured_at < before. Nếu không truyền endpoint thì xóa trên tất cả host. Dùng để tránh storage phình theo thời gian.
// @Tags        snapshot
// @Produce     json
// @Param       before    query  string  true   "RFC3339 — xóa snapshot trước thời điểm này (ví dụ: 2025-01-01T00:00:00Z)"
// @Param       endpoint  query  string  false  "Chỉ xóa snapshot của endpoint này (bỏ trống = tất cả)"
// @Success     200  {object}  DeleteSnapshotsResponse
// @Failure     400  {object}  map[string]string
// @Failure     500  {object}  map[string]string
// @Failure     503  {object}  map[string]string
// @Router      /mongodb-cmd/snapshots [delete]
func (inst *handler) DeleteSnapshots(c *gin.Context) {
	if inst.Storage == nil {
		c.JSON(http.StatusServiceUnavailable, gin.H{"error": "storage not configured"})
		return
	}

	var req DeleteSnapshotsQuery
	if err := c.ShouldBindQuery(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	before, err := time.Parse(time.RFC3339, req.Before)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid before (expect RFC3339): " + err.Error()})
		return
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 30*time.Second)
	defer cancel()

	deleted, err := inst.Storage.DeleteBefore(ctx, before, req.Endpoint)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, DeleteSnapshotsResponse{
		Before:       req.Before,
		Endpoint:     req.Endpoint,
		DeletedCount: deleted,
	})
}

// ─── Part 5: COLLSCAN Stats ───────────────────────────────────────────────────

type CollscanStatsQuery struct {
	Endpoint   string `form:"endpoint" binding:"required"`
	Database   string `form:"database" binding:"required"`
	Collection string `form:"collection"`
	From       string `form:"from"`
	To         string `form:"to"`
	Limit      *int64 `form:"limit"`
}

// GetCollscanStats godoc
// @Summary     Thống kê COLLSCAN từ system.profile
// @Description Trả về danh sách collection bị collection scan (COLLSCAN) nhiều nhất trong khoảng thời gian, kèm avg/max ms và 5 sample query.
// @Tags        analytics
// @Produce     json
// @Param       endpoint    query  string  true   "MongoDB host"
// @Param       database    query  string  true   "Tên database"
// @Param       collection  query  string  false  "Lọc theo collection"
// @Param       from        query  string  false  "RFC3339 — mặc định 24h trước (ví dụ: 2025-01-01T00:00:00Z)"
// @Param       to          query  string  false  "RFC3339 — mặc định now"
// @Param       limit       query  integer false  "Số collection trả về tối đa (mặc định 20)"
// @Success     200  {array}   map[string]interface{}
// @Failure     400  {object}  map[string]string
// @Failure     500  {object}  map[string]string
// @Router      /mongodb-cmd/collscan-stats [get]
func (inst *handler) GetCollscanStats(c *gin.Context) {
	var req CollscanStatsQuery
	if err := c.ShouldBindQuery(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	client, exists := inst.MongoClients[req.Endpoint]
	if !exists {
		c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("endpoint %s not found", req.Endpoint)})
		return
	}

	toTime := time.Now().UTC()
	fromTime := toTime.Add(-24 * time.Hour)
	if req.From != "" {
		t, err := time.Parse(time.RFC3339, req.From)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid from: " + err.Error()})
			return
		}
		fromTime = t
	}
	if req.To != "" {
		t, err := time.Parse(time.RFC3339, req.To)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid to: " + err.Error()})
			return
		}
		toTime = t
	}

	limit := int64(20)
	if req.Limit != nil && *req.Limit > 0 {
		limit = *req.Limit
	}

	matchFilter := bson.D{
		{Key: "planSummary", Value: bson.M{"$regex": "COLLSCAN"}},
		{Key: "ts", Value: bson.M{"$gte": fromTime, "$lte": toTime}},
	}
	if req.Collection != "" {
		matchFilter = append(matchFilter, bson.E{Key: "ns", Value: fmt.Sprintf("%s.%s", req.Database, req.Collection)})
	}

	pipeline := mongo.Pipeline{
		{{Key: "$match", Value: matchFilter}},
		{{Key: "$group", Value: bson.D{
			{Key: "_id", Value: "$ns"},
			{Key: "count", Value: bson.D{{Key: "$sum", Value: 1}}},
			{Key: "total_millis", Value: bson.D{{Key: "$sum", Value: "$millis"}}},
			{Key: "max_millis", Value: bson.D{{Key: "$max", Value: "$millis"}}},
			{Key: "avg_millis", Value: bson.D{{Key: "$avg", Value: "$millis"}}},
			{Key: "sample_queries", Value: bson.D{{Key: "$push", Value: bson.D{
				{Key: "ts", Value: "$ts"},
				{Key: "millis", Value: "$millis"},
				{Key: "query_hash", Value: "$queryHash"},
				{Key: "plan_summary", Value: "$planSummary"},
				{Key: "command", Value: "$command"},
			}}}},
		}}},
		{{Key: "$project", Value: bson.D{
			{Key: "_id", Value: 0},
			{Key: "namespace", Value: "$_id"},
			{Key: "count", Value: 1},
			{Key: "total_millis", Value: 1},
			{Key: "max_millis", Value: 1},
			{Key: "avg_millis", Value: 1},
			// Chỉ lấy 5 sample query đầu để tránh response quá lớn
			{Key: "sample_queries", Value: bson.D{{Key: "$slice", Value: bson.A{"$sample_queries", 5}}}},
		}}},
		{{Key: "$sort", Value: bson.D{{Key: "count", Value: -1}}}},
		{{Key: "$limit", Value: limit}},
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 30*time.Second)
	defer cancel()

	cursor, err := client.Database(req.Database).Collection("system.profile").Aggregate(ctx, pipeline)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	var results []bson.M
	if err = cursor.All(ctx, &results); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if results == nil {
		results = []bson.M{}
	}
	c.JSON(http.StatusOK, results)
}

// ─── Part 6: Index Correlation ────────────────────────────────────────────────

type IndexCorrelationQuery struct {
	Database   string `form:"database"`
	Collection string `form:"collection"`
	From       string `form:"from"`
	To         string `form:"to"`
}

// IndexCorrelationResult kết hợp index usage delta + COLLSCAN stats cho 1 collection.
// HasSuspectedMissingIndex = true khi collection bị COLLSCAN nhưng lại có index chưa dùng.
type IndexCorrelationResult struct {
	Endpoint                 string                `json:"endpoint"`
	Database                 string                `json:"database"`
	Collection               string                `json:"collection"`
	From                     time.Time             `json:"from"`
	To                       time.Time             `json:"to"`
	SingleSnapshot           bool                  `json:"single_snapshot,omitempty"`
	Indexes                  []snapshot.IndexDelta `json:"indexes"`
	CollscanCount            int64                 `json:"collscan_count"`
	CollscanAvgMs            float64               `json:"collscan_avg_ms"`
	CollscanMaxMs            float64               `json:"collscan_max_ms"`
	HasSuspectedMissingIndex bool                  `json:"has_suspected_missing_index"`
}

// GetIndexCorrelation godoc
// @Summary     Tương quan index usage với COLLSCAN để tìm missing index
// @Description Kết hợp index usage delta (từ snapshots) với số lần COLLSCAN (từ system.profile) để xác định collection có khả năng thiếu index. has_suspected_missing_index=true khi collection bị COLLSCAN nhưng có index chưa dùng.
// @Tags        analytics
// @Produce     json
// @Param       database    query  string  false  "Lọc theo database"
// @Param       collection  query  string  false  "Lọc theo collection"
// @Param       from        query  string  false  "RFC3339 — mặc định 24h trước"
// @Param       to          query  string  false  "RFC3339 — mặc định now"
// @Success     200  {array}   IndexCorrelationResult
// @Failure     400  {object}  map[string]string
// @Failure     404  {object}  map[string]string
// @Failure     500  {object}  map[string]string
// @Failure     503  {object}  map[string]string
// @Router      /mongodb-cmd/index-correlation [get]
func (inst *handler) GetIndexCorrelation(c *gin.Context) {
	if inst.Storage == nil {
		c.JSON(http.StatusServiceUnavailable, gin.H{"error": "storage not configured"})
		return
	}

	var req IndexCorrelationQuery
	if err := c.ShouldBindQuery(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	toTime := time.Now().UTC()
	fromTime := toTime.Add(-24 * time.Hour)
	if req.From != "" {
		t, err := time.Parse(time.RFC3339, req.From)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid from: " + err.Error()})
			return
		}
		fromTime = t
	}
	if req.To != "" {
		t, err := time.Parse(time.RFC3339, req.To)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid to: " + err.Error()})
			return
		}
		toTime = t
	}

	endpoints := make([]string, 0, len(inst.MongoClients))
	for ep := range inst.MongoClients {
		endpoints = append(endpoints, ep)
	}

	ctx := c.Request.Context()
	targets, err := inst.Storage.ListTargets(ctx, endpoints, req.Database, req.Collection, toTime)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if len(targets) == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": "no snapshots found — collector may not have run yet"})
		return
	}

	results := make([]IndexCorrelationResult, 0, len(targets))
	for _, t := range targets {
		// ── 1. Tính index delta (giống index-stats) ──────────────────────────
		snapA, err := inst.Storage.FindClosestBefore(ctx, t.Endpoint, t.Database, t.Collection, fromTime)
		if err != nil {
			snapA, err = inst.Storage.FindEarliest(ctx, t.Endpoint, t.Database, t.Collection, fromTime)
			if err != nil {
				log.Printf("[Correlation] no snapshot for %s/%s/%s: %v", t.Endpoint, t.Database, t.Collection, err)
				continue
			}
		}
		snapB, err := inst.Storage.FindClosestBefore(ctx, t.Endpoint, t.Database, t.Collection, toTime)
		if err != nil {
			continue
		}

		var delta snapshot.DeltaResult
		if snapA.ID == snapB.ID {
			delta = snapshot.SingleSnapshotResult(snapB)
		} else {
			between, _ := inst.Storage.FindBetween(ctx, t.Endpoint, t.Database, t.Collection, snapA.CapturedAt, snapB.CapturedAt)
			delta = snapshot.CalcDelta(snapA, snapB, between)
		}

		// ── 2. Query COLLSCAN stats từ system.profile ────────────────────────
		var collscanCount int64
		var collscanAvgMs, collscanMaxMs float64

		if mongoClient, ok := inst.MongoClients[t.Endpoint]; ok {
			collscanPipeline := mongo.Pipeline{
				{{Key: "$match", Value: bson.D{
					{Key: "ns", Value: fmt.Sprintf("%s.%s", t.Database, t.Collection)},
					{Key: "planSummary", Value: bson.M{"$regex": "COLLSCAN"}},
					{Key: "ts", Value: bson.M{"$gte": fromTime, "$lte": toTime}},
				}}},
				{{Key: "$group", Value: bson.D{
					{Key: "_id", Value: nil},
					{Key: "count", Value: bson.D{{Key: "$sum", Value: 1}}},
					{Key: "avg_ms", Value: bson.D{{Key: "$avg", Value: "$millis"}}},
					{Key: "max_ms", Value: bson.D{{Key: "$max", Value: "$millis"}}},
				}}},
			}
			qCtx, qCancel := context.WithTimeout(ctx, 10*time.Second)
			cursor, err := mongoClient.Database(t.Database).Collection("system.profile").Aggregate(qCtx, collscanPipeline)
			qCancel()
			if err == nil {
				var agg []bson.M
				if cursor.All(qCtx, &agg) == nil && len(agg) > 0 { //nolint:contextcheck
					collscanCount = int64Field(agg[0], "count")
					collscanAvgMs = float64Field(agg[0], "avg_ms")
					collscanMaxMs = float64Field(agg[0], "max_ms")
				}
			}
		}

		// ── 3. Kiểm tra có index nào delta == 0 không khi đang bị COLLSCAN ──
		hasSuspect := false
		if collscanCount > 0 {
			for _, idx := range delta.Indexes {
				if idx.Delta == 0 {
					hasSuspect = true
					break
				}
			}
		}

		results = append(results, IndexCorrelationResult{
			Endpoint:                 delta.Endpoint,
			Database:                 delta.Database,
			Collection:               delta.Collection,
			From:                     delta.From,
			To:                       delta.To,
			SingleSnapshot:           delta.SingleSnapshot,
			Indexes:                  delta.Indexes,
			CollscanCount:            collscanCount,
			CollscanAvgMs:            collscanAvgMs,
			CollscanMaxMs:            collscanMaxMs,
			HasSuspectedMissingIndex: hasSuspect,
		})
	}

	c.JSON(http.StatusOK, results)
}

// float64Field đọc field dạng số từ bson.M, trả về float64
func float64Field(m bson.M, key string) float64 {
	switch v := m[key].(type) {
	case float64:
		return v
	case int32:
		return float64(v)
	case int64:
		return float64(v)
	}
	return 0
}

// int64Field đọc field dạng số từ bson.M, trả về int64
func int64Field(m bson.M, key string) int64 {
	switch v := m[key].(type) {
	case int32:
		return int64(v)
	case int64:
		return v
	case float64:
		return int64(v)
	}
	return 0
}

// @title           MongoDB Profiler API
// @version         1.0
// @description     Real-time monitoring for MongoDB: slow queries, index usage, COLLSCAN detection, and current operations.
// @host            localhost:8082
// @BasePath        /
// @schemes         http https
func main() {
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatal(err)
	}

	handler := NewHandler(cfg)

	// --- Setup snapshot storage ---
	// Dùng lại cụm mongodb đã cấu hình, không cần URI riêng
	storageClient, err := newStorageClient(cfg)
	if err != nil {
		log.Fatalf("Failed to connect to storage MongoDB: %v", err)
	}
	store := snapshot.NewStorage(storageClient.Database(cfg.Storage.Database), cfg.Snapshot.RetentionDays)
	handler.Storage = store // cho GetIndexCorrelation dùng

	idxCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	if err := store.EnsureIndexes(idxCtx); err != nil {
		log.Printf("[Warning] Failed to create storage indexes: %v", err)
	}
	cancel()

	// Start background snapshot collector
	intervalMinutes := cfg.Snapshot.IntervalMinutes
	if intervalMinutes <= 0 {
		intervalMinutes = 60
	}
	collector := snapshot.NewCollector(handler.MongoClients, store, intervalMinutes, cfg.Storage.Database)
	collector.Start(context.Background())
	log.Printf("Snapshot collector started, interval: %d minutes", intervalMinutes)

	r := gin.Default()

	// Swagger UI — truy cập tại /swagger/index.html
	r.GET("/mongodb-cmd/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler,
		ginSwagger.URL("/mongodb-cmd/swagger/doc.json"),
	))

	r.GET("/mongodb-cmd/profiles", handler.GetProfiles)
	r.GET("/mongodb-cmd/profile", handler.GetProfile)
	r.DELETE("/mongodb-cmd/profile/query-hash", handler.DeleteProfileByQueryHash)
	r.GET("/mongodb-cmd/collscan-stats", handler.GetCollscanStats)
	r.GET("/mongodb-cmd/index-correlation", handler.GetIndexCorrelation)

	currentOpHandler := &currentop.Handler{MongoClients: handler.MongoClients}
	r.GET("/mongodb-cmd/current-ops", currentOpHandler.GetCurrentOps)

	rsHandler := &replicaset.Handler{MongoClients: handler.MongoClients}
	r.GET("/mongodb-cmd/replica-status", rsHandler.GetReplicaStatus)

	r.DELETE("/mongodb-cmd/snapshots", handler.DeleteSnapshots)

	// Index stats chỉ available khi storage đã được cấu hình
	if store != nil {
		endpoints := make([]string, 0, len(handler.MongoClients))
		for ep := range handler.MongoClients {
			endpoints = append(endpoints, ep)
		}
		idxHandler := &indexstats.Handler{Storage: store, Endpoints: endpoints}
		r.GET("/mongodb-cmd/index-stats", idxHandler.GetIndexStats)
		log.Println("Route /mongodb-cmd/index-stats enabled")
	}

	fmt.Printf("Server running on :%d\n", cfg.Server.Port)

	if err := r.Run(fmt.Sprintf(":%d", cfg.Server.Port)); err != nil {
		log.Fatal(err)
	}
}
